// Tłumaczenia modułu Pogoda (generowane z tabeli; klucze p.*)
I18N.add({
"pl": {
"p.act.wozek": "Wózek",
"p.act.nosidlo": "Nosidło",
"p.act.spacer": "Spacer",
"p.act.plac": "Plac zabaw",
"p.act.wozek.d": "leży lub siedzi",
"p.act.nosidlo.d": "przy rodzicu",
"p.act.spacer.d": "idzie sam",
"p.act.plac.d": "biega",
"p.band.hot": "Upał",
"p.band.warm": "Ciepło",
"p.band.mild": "Łagodnie",
"p.band.cool": "Chłodno",
"p.band.cold": "Zimno",
"p.band.frost": "Bardzo zimno",
"p.band.severe": "Ekstremalnie zimno",
"p.why.newborn": "noworodek −1°",
"p.why.long": "długi spacer −1°",
"p.o.hot.b1": "Samo body z krótkim rękawem lub bez rękawów (bawełna, len)",
"p.o.hot.b2": "Luźna koszulka z krótkim rękawem (bawełna, len)",
"p.o.hot.l1": "Tylko pielucha albo cienkie szorty",
"p.o.hot.l2": "Krótkie spodenki lub przewiewna sukienka",
"p.o.hot.f1": "Sandały z zakrytymi palcami",
"p.o.hot.f2": "Boso",
"p.o.hot.h": "Kapelusz z rondem, jasny, przewiewny",
"p.o.warm.b1": "Koszulka lub body z krótkim rękawem",
"p.o.warm.b2": "Cienka bluza rozpinana",
"p.o.warm.l": "Cienkie długie spodnie lub legginsy",
"p.o.warm.f1": "Skarpetki i lekkie buty",
"p.o.warm.f2": "Cienkie skarpetki",
"p.o.warm.h1": "Kapelusz lub czapka z daszkiem",
"p.o.warm.h2": "Cienka czapeczka, tylko przy wietrze",
"p.o.warm.h3": "Bez czapki",
"p.o.mild.b1": "Body lub koszulka z długim rękawem",
"p.o.mild.b2": "Cienka bluza lub sweterek",
"p.o.mild.b3": "Wiatrówka lub cienka kurtka",
"p.o.mild.b4": "Cienka kurtka",
"p.o.mild.l": "Długie spodnie (dresowe, bawełniane)",
"p.o.mild.f1": "Skarpetki i pełne buty",
"p.o.mild.f2": "Skarpetki",
"p.o.mild.h1": "Cienka bawełniana czapka",
"p.o.mild.h2": "Cienka czapka przy wietrze",
"p.o.cool.b2": "Polar lub bluza",
"p.o.cool.b3": "Kurtka przejściowa",
"p.o.cool.l1": "Rajstopki + długie spodnie",
"p.o.cool.l2": "Długie spodnie",
"p.o.cool.f1": "Grubsze skarpety i buty przejściowe",
"p.o.cool.f2": "Grubsze skarpety",
"p.o.cool.h": "Cienka czapka zakrywająca uszy",
"p.o.cool.n": "Komin lub chustka",
"p.o.cool.hd": "Cienkie rękawiczki",
"p.o.cold.b2": "Polar lub sweter",
"p.o.cold.b3a": "Kombinezon ocieplany",
"p.o.cold.b3b": "Kurtka ocieplana",
"p.o.cold.l1": "Rajstopy + spodnie (pod kombinezon)",
"p.o.cold.l2": "Rajstopy + spodnie lub spodnie ocieplane",
"p.o.cold.f1": "Ciepłe skarpety i buty ocieplane",
"p.o.cold.f2": "Ciepłe skarpety lub papcie do wózka",
"p.o.cold.h": "Ciepła czapka na uszy",
"p.o.cold.n": "Komin",
"p.o.cold.hd1": "Rękawiczki",
"p.o.cold.hd2": "Łapki niemowlęce",
"p.o.frost.b1": "Bielizna termoaktywna lub body z wełny merino",
"p.o.frost.b2": "Polar lub wełniany sweter",
"p.o.frost.b3": "Kombinezon zimowy",
"p.o.frost.l": "Rajstopy wełniane lub legginsy termo (pod kombinezon)",
"p.o.frost.f1": "Wełniane skarpety i buty zimowe",
"p.o.frost.f2": "Wełniane skarpety, buciki lub śpiworek zakrywający stopy",
"p.o.frost.h1": "Kominiarka i zimowa czapka",
"p.o.frost.h2": "Zimowa czapka, ewentualnie kominiarka",
"p.o.frost.n": "Komin polarowy",
"p.o.frost.hd": "Nieprzemakalne łapki",
"p.o.wet.b": "Kurtka przeciwdeszczowa jako wierzchnia warstwa",
"p.o.wet.l": "Spodnie przeciwdeszczowe na wierzch",
"p.o.wet.f1": "Kalosze z ciepłą wkładką",
"p.o.wet.f2": "Kalosze",
"p.o.snow.l": "Spodnie nieprzemakalne (śnieg)",
"p.o.snow.hd": "Zapasowa para rękawiczek",
"p.o.plac.1": "Zapasowe skarpetki i spodnie",
"p.o.plac.2": "Bluzę zdejmij po 10 min zabawy, jeśli się grzeje",
"p.o.st.1": "Bez kocyka. Nie zasłaniaj budki pieluszką, bo w środku robi się gorąco",
"p.o.st.2": "Cienki kocyk muślinowy",
"p.o.st.3": "Kocyk lub cienki śpiworek",
"p.o.st.4": "Śpiwór do wózka",
"p.o.st.5": "Zimowy śpiwór do wózka i osłona od wiatru",
"p.o.st.rain": "Folia przeciwdeszczowa, uchylona dla wentylacji",
"p.o.st.wind": "Budka ustawiona od strony wiatru",
"p.o.car.1": "Dziecko ubierz o jedną warstwę lżej. Ciepło rodzica grzeje",
"p.o.car.2": "Kurtka lub osłona nosidłowa rodzica, ciepłe skarpety (stopy wystają)",
"p.a.severe.t": "Rozważ krótszy spacer",
"p.a.severe.i": "Przy tak odczuwalnej temperaturze niemowlę wyjdź maksymalnie na 15–20 minut albo zostańcie w domu.",
"p.a.severe.w": "Wyjdźcie na 20–30 minut i obserwujcie policzki i nos.",
"p.a.heat": "Unikaj wyjścia między 11 a 16. Częściej podawaj pierś, mleko lub wodę (wodę od 6. miesiąca). Szukaj cienia.",
"p.a.uv.inf": "Niemowlę do 6. miesiąca trzymaj w cieniu i chroń ubraniem oraz budką. Kremów z filtrem u tak małych dzieci się unika.",
"p.a.rain.t": "Może padać",
"p.a.rain.car": "Weź parasol lub osłonę przeciwdeszczową na nosidło.",
"p.a.rain.st": "Folia na wózek w koszu.",
"p.a.rain.w": "Ubranie przeciwdeszczowe już jest na liście.",
"p.a.wind.t": "Silny wiatr",
"p.a.seat.t": "Fotelik samochodowy",
"p.a.seat": "Przed zapięciem w foteliku zdejmij kurtkę lub kombinezon. Gruba warstwa luzuje pasy. Okryj dziecko kocem na pasy.",
"p.a.neck.t": "Test karku",
"p.a.neck": "Dotknij karku po 10 minutach. Ciepły i suchy: dobrze. Spocony: zdejmij warstwę. Chłodny: dołóż. Zimne dłonie są normalne i niczego nie mówią.",
"p.r.snow": "śnieg",
"p.r.now": "Teraz",
"p.r.sample": "Przykładowa prognoza. Po uruchomieniu aplikacji z własnego adresu pobierze się prawdziwa pogoda dla Twojej lokalizacji.",
"p.r.err": "Brak połączenia z serwisem pogodowym w tym podglądzie. Pokazuję przykładową jesienną prognozę. Po wdrożeniu na własny adres aplikacja pobiera prawdziwą pogodę.",
"p.sl.head": "Głowa",
"p.sl.neck": "Szyja",
"p.sl.body": "Tułów",
"p.sl.legs": "Nogi",
"p.sl.feet": "Stopy",
"p.sl.hands": "Dłonie",
"p.sl.bag": "Do torby",
"p.kid.default": "Maluch",
"p.loc.yours": "Twoja lokalizacja",
"p.s.feel.cold": "Zmarzluch",
"p.s.feel.typ": "Typowo",
"p.s.feel.hot": "Szybko się poci",
"p.s.findloc": "Szukam lokalizacji…",
"p.s.locfail": "Nie udało się pobrać lokalizacji. Zezwól na dostęp w przeglądarce albo wpisz miejscowość.",
"p.settings": "Ustawienia",
"p.ex.b": "Przykładowe dziecko.",
"p.ex.d": "Ustaw swoje w 3 krokach, a rekomendacja dopasuje się do wieku.",
"p.ex.go": "Zacznij",
"p.wx": "Pogoda",
"p.when": "Kiedy wychodzicie?",
"p.what": "Co robicie",
"p.dur": "Jak długo",
"p.rec": "Rekomendacja",
"p.outfit": "Co założyć",
"p.outfit.h": "Co założyć · od skóry na zewnątrz",
"p.tips": "Wskazówki",
"p.m.sum": "Zmień warunki ręcznie",
"p.m.d": "Nadpisuje prognozę. Przydatne do sprawdzenia, jak zmieni się ubiór.",
"p.m.t": "Odczuwalna °C",
"p.m.w": "Wiatr km/h",
"p.m.p": "Szansa opadów %",
"p.m.u": "Indeks UV",
"p.m.k": "Opad",
"p.k.none": "brak",
"p.k.rain": "deszcz",
"p.k.snow": "śnieg",
"p.m.apply": "Przelicz",
"p.m.reset": "Wróć do prognozy",
"p.f.back": "← Wszystkie moduły",
"p.f.note": " · Pogoda: Open-Meteo. Wskazówki mają charakter ogólny. Zawsze sprawdź kark dziecka.",
"p.feels": "odczuwalna {v}°",
"p.stat.wind": "Wiatr",
"p.stat.max": "Maks. dziś",
"p.stat.min": "Min.",
"p.kmh": "km/h",
"p.addkid": "+ dziecko",
"p.why.cold": "zmarzluch {v}°",
"p.why.warm": "szybko się grzeje +{v}°",
"p.a.frost": "Skróć spacer do 30–40 minut. Na policzki tłusty krem ochronny na zimno (bez wody), 20 minut przed wyjściem.",
"p.a.uv": "Krem z filtrem SPF 50 (mineralny) na odkrytą skórę{x}.",
"p.a.uv.glasses": ", okulary UV400",
"p.a.rain": "Szansa opadów do {p}%. {x}",
"p.a.wind": "Porywy do {v} km/h. Komin, osłona twarzy, unikaj otwartych przestrzeni.",
"p.v.label": "{name} · {age} · wyjście {time}",
"p.v.manual": "(ręcznie)",
"p.v.title": "{band}: {n} {w} na tułów",
"p.v.why": "Temperatura dla dziecka {T}°. Liczona z najniższej odczuwalnej w czasie spaceru ({f}°) i korekt: {why}.",
"p.s.step": "Krok {n} z 3",
"p.s.who": "Kogo ubieramy?",
"p.s.name": "Imię lub przydomek",
"p.s.name.ph": "np. Staś",
"p.s.birth": "Miesiąc urodzenia",
"p.s.feel": "Jak znosi chłód?",
"p.s.cancel": "Anuluj",
"p.s.next": "Dalej",
"p.s.back": "Wstecz",
"p.s.where": "Gdzie spacerujecie?",
"p.s.gps": "Użyj mojej lokalizacji",
"p.s.cur": "Obecnie: {v}",
"p.s.city": "albo wpisz miejscowość",
"p.s.city.ph": "np. Siemianowice Śląskie",
"p.s.nores": "Brak wyników.",
"p.s.geofail": "Wyszukiwarka miejscowości nie odpowiada. Spróbuj później.",
"p.s.how": "Jak zwykle wychodzicie?",
"p.s.later": "Możesz to zmienić przy każdym wyjściu.",
"p.s.done": "Gotowe",
"p.title": "Pogoda · Wyprawka",
"p.wmo.0": "Bezchmurnie",
"p.wmo.1": "Przeważnie słonecznie",
"p.wmo.2": "Częściowe zachmurzenie",
"p.wmo.3": "Pochmurno",
"p.wmo.45": "Mgła",
"p.wmo.48": "Szadź",
"p.wmo.51": "Lekka mżawka",
"p.wmo.53": "Mżawka",
"p.wmo.55": "Gęsta mżawka",
"p.wmo.56": "Marznąca mżawka",
"p.wmo.57": "Marznąca mżawka",
"p.wmo.61": "Słaby deszcz",
"p.wmo.63": "Deszcz",
"p.wmo.65": "Ulewa",
"p.wmo.66": "Marznący deszcz",
"p.wmo.67": "Marznący deszcz",
"p.wmo.71": "Słaby śnieg",
"p.wmo.73": "Śnieg",
"p.wmo.75": "Intensywny śnieg",
"p.wmo.77": "Ziarna śniegu",
"p.wmo.80": "Przelotny deszcz",
"p.wmo.81": "Przelotne opady",
"p.wmo.82": "Gwałtowne opady",
"p.wmo.85": "Przelotny śnieg",
"p.wmo.86": "Śnieżyca",
"p.wmo.95": "Burza",
"p.wmo.96": "Burza z gradem",
"p.wmo.99": "Burza z gradem",
"p.wmo.undefined": "–"
},
"en": {
"p.act.wozek": "Stroller",
"p.act.nosidlo": "Carrier",
"p.act.spacer": "Walk",
"p.act.plac": "Playground",
"p.act.wozek.d": "lying or sitting",
"p.act.nosidlo.d": "close to the parent",
"p.act.spacer.d": "walks on their own",
"p.act.plac.d": "runs around",
"p.band.hot": "Heat",
"p.band.warm": "Warm",
"p.band.mild": "Mild",
"p.band.cool": "Cool",
"p.band.cold": "Cold",
"p.band.frost": "Very cold",
"p.band.severe": "Extremely cold",
"p.why.newborn": "newborn −1°",
"p.why.long": "long walk −1°",
"p.o.hot.b1": "Just a short-sleeve or sleeveless bodysuit (cotton, linen)",
"p.o.hot.b2": "Loose short-sleeve T-shirt (cotton, linen)",
"p.o.hot.l1": "Just a nappy or thin shorts",
"p.o.hot.l2": "Shorts or an airy dress",
"p.o.hot.f1": "Closed-toe sandals",
"p.o.hot.f2": "Barefoot",
"p.o.hot.h": "Light-coloured, breathable wide-brim hat",
"p.o.warm.b1": "Short-sleeve T-shirt or bodysuit",
"p.o.warm.b2": "Thin zip-up top",
"p.o.warm.l": "Thin long trousers or leggings",
"p.o.warm.f1": "Socks and light shoes",
"p.o.warm.f2": "Thin socks",
"p.o.warm.h1": "Sun hat or cap",
"p.o.warm.h2": "Thin hat, only if windy",
"p.o.warm.h3": "No hat",
"p.o.mild.b1": "Long-sleeve bodysuit or top",
"p.o.mild.b2": "Thin top or light jumper",
"p.o.mild.b3": "Windbreaker or light jacket",
"p.o.mild.b4": "Light jacket",
"p.o.mild.l": "Long trousers (joggers, cotton)",
"p.o.mild.f1": "Socks and closed shoes",
"p.o.mild.f2": "Socks",
"p.o.mild.h1": "Thin cotton hat",
"p.o.mild.h2": "Thin hat if windy",
"p.o.cool.b2": "Fleece or sweatshirt",
"p.o.cool.b3": "Transitional jacket",
"p.o.cool.l1": "Tights + long trousers",
"p.o.cool.l2": "Long trousers",
"p.o.cool.f1": "Thicker socks and transitional shoes",
"p.o.cool.f2": "Thicker socks",
"p.o.cool.h": "Thin hat covering the ears",
"p.o.cool.n": "Snood or scarf",
"p.o.cool.hd": "Thin gloves",
"p.o.cold.b2": "Fleece or jumper",
"p.o.cold.b3a": "Insulated snowsuit",
"p.o.cold.b3b": "Insulated jacket",
"p.o.cold.l1": "Tights + trousers (under the snowsuit)",
"p.o.cold.l2": "Tights + trousers or insulated trousers",
"p.o.cold.f1": "Warm socks and insulated shoes",
"p.o.cold.f2": "Warm socks or stroller booties",
"p.o.cold.h": "Warm hat covering the ears",
"p.o.cold.n": "Snood",
"p.o.cold.hd1": "Gloves",
"p.o.cold.hd2": "Baby mittens",
"p.o.frost.b1": "Thermal base layer or merino wool bodysuit",
"p.o.frost.b2": "Fleece or wool jumper",
"p.o.frost.b3": "Winter snowsuit",
"p.o.frost.l": "Wool tights or thermal leggings (under the snowsuit)",
"p.o.frost.f1": "Wool socks and winter boots",
"p.o.frost.f2": "Wool socks, booties or a footmuff covering the feet",
"p.o.frost.h1": "Balaclava and winter hat",
"p.o.frost.h2": "Winter hat, possibly a balaclava",
"p.o.frost.n": "Fleece snood",
"p.o.frost.hd": "Waterproof mittens",
"p.o.wet.b": "Rain jacket as the outer layer",
"p.o.wet.l": "Rain trousers on top",
"p.o.wet.f1": "Wellies with a warm liner",
"p.o.wet.f2": "Wellies",
"p.o.snow.l": "Waterproof trousers (snow)",
"p.o.snow.hd": "Spare pair of gloves",
"p.o.plac.1": "Spare socks and trousers",
"p.o.plac.2": "Take off the top after 10 min of play if they're getting hot",
"p.o.st.1": "No blanket. Don't cover the hood with a cloth: it gets hot inside",
"p.o.st.2": "Thin muslin blanket",
"p.o.st.3": "Blanket or thin footmuff",
"p.o.st.4": "Stroller footmuff",
"p.o.st.5": "Winter footmuff and wind cover",
"p.o.st.rain": "Rain cover, slightly open for ventilation",
"p.o.st.wind": "Hood turned towards the wind",
"p.o.car.1": "Dress the child one layer lighter. The parent's body warms them",
"p.o.car.2": "Parent's babywearing jacket or carrier cover, warm socks (feet stick out)",
"p.a.severe.t": "Consider a shorter walk",
"p.a.severe.i": "At this feels-like temperature, take an infant out for 15–20 minutes at most, or stay at home.",
"p.a.severe.w": "Go out for 20–30 minutes and watch the cheeks and nose.",
"p.a.heat": "Avoid going out between 11:00 and 16:00. Offer the breast, milk or water more often (water from 6 months). Seek shade.",
"p.a.uv.inf": "Keep babies under 6 months in the shade, protected by clothing and the hood. Sunscreen is avoided at this age.",
"p.a.rain.t": "Rain likely",
"p.a.rain.car": "Take an umbrella or a rain cover for the carrier.",
"p.a.rain.st": "Rain cover in the stroller basket.",
"p.a.rain.w": "Rain gear is already on the list.",
"p.a.wind.t": "Strong wind",
"p.a.seat.t": "Car seat",
"p.a.seat": "Take off the jacket or snowsuit before buckling into the car seat. Thick layers loosen the harness. Put a blanket over the straps instead.",
"p.a.neck.t": "Neck test",
"p.a.neck": "Touch the back of the neck after 10 minutes. Warm and dry: good. Sweaty: remove a layer. Cool: add one. Cold hands are normal and tell you nothing.",
"p.r.snow": "snow",
"p.r.now": "Now",
"p.r.sample": "Sample forecast. When the app runs from its own address, it fetches real weather for your location.",
"p.r.err": "No connection to the weather service in this preview. Showing a sample autumn forecast. Once deployed to its own address, the app fetches real weather.",
"p.sl.head": "Head",
"p.sl.neck": "Neck",
"p.sl.body": "Torso",
"p.sl.legs": "Legs",
"p.sl.feet": "Feet",
"p.sl.hands": "Hands",
"p.sl.bag": "In the bag",
"p.kid.default": "Little one",
"p.loc.yours": "Your location",
"p.s.feel.cold": "Feels the cold",
"p.s.feel.typ": "Typical",
"p.s.feel.hot": "Sweats easily",
"p.s.findloc": "Finding your location…",
"p.s.locfail": "Couldn't get your location. Allow access in the browser or type a town.",
"p.settings": "Settings",
"p.ex.b": "Sample child.",
"p.ex.d": "Set up yours in 3 steps and the advice will match their age.",
"p.ex.go": "Start",
"p.wx": "Weather",
"p.when": "When are you going out?",
"p.what": "What are you doing",
"p.dur": "How long",
"p.rec": "Recommendation",
"p.outfit": "What to wear",
"p.outfit.h": "What to wear · from the skin out",
"p.tips": "Tips",
"p.m.sum": "Set conditions manually",
"p.m.d": "Overrides the forecast. Handy for checking how the outfit changes.",
"p.m.t": "Feels like °C",
"p.m.w": "Wind km/h",
"p.m.p": "Chance of rain %",
"p.m.u": "UV index",
"p.m.k": "Precipitation",
"p.k.none": "none",
"p.k.rain": "rain",
"p.k.snow": "snow",
"p.m.apply": "Recalculate",
"p.m.reset": "Back to forecast",
"p.f.back": "← All modules",
"p.f.note": " · Weather: Open-Meteo. Advice is general. Always check your child's neck.",
"p.feels": "feels like {v}°",
"p.stat.wind": "Wind",
"p.stat.max": "Today's max",
"p.stat.min": "Min",
"p.kmh": "km/h",
"p.addkid": "+ child",
"p.why.cold": "feels the cold {v}°",
"p.why.warm": "runs warm +{v}°",
"p.a.frost": "Keep the walk to 30–40 minutes. Put a rich, water-free cold-weather cream on the cheeks 20 minutes before going out.",
"p.a.uv": "Mineral SPF 50 sunscreen on exposed skin{x}.",
"p.a.uv.glasses": ", UV400 sunglasses",
"p.a.rain": "Chance of rain up to {p}%. {x}",
"p.a.wind": "Gusts up to {v} km/h. Snood, face cover, avoid open spaces.",
"p.v.label": "{name} · {age} · out at {time}",
"p.v.manual": "(manual)",
"p.v.title": "{band}: {n} {w} on the torso",
"p.v.why": "Temperature for the child: {T}°. Based on the lowest feels-like temperature during the walk ({f}°) and adjustments: {why}.",
"p.s.step": "Step {n} of 3",
"p.s.who": "Who are we dressing?",
"p.s.name": "Name or nickname",
"p.s.name.ph": "e.g. Sam",
"p.s.birth": "Birth month",
"p.s.feel": "How do they handle the cold?",
"p.s.cancel": "Cancel",
"p.s.next": "Next",
"p.s.back": "Back",
"p.s.where": "Where do you go for walks?",
"p.s.gps": "Use my location",
"p.s.cur": "Current: {v}",
"p.s.city": "or type a town",
"p.s.city.ph": "e.g. Kraków",
"p.s.nores": "No results.",
"p.s.geofail": "Town search isn't responding. Try again later.",
"p.s.how": "How do you usually go out?",
"p.s.later": "You can change this every time you go out.",
"p.s.done": "Done",
"p.title": "Weather · Wyprawka",
"p.wmo.0": "Clear sky",
"p.wmo.1": "Mostly sunny",
"p.wmo.2": "Partly cloudy",
"p.wmo.3": "Overcast",
"p.wmo.45": "Fog",
"p.wmo.48": "Rime fog",
"p.wmo.51": "Light drizzle",
"p.wmo.53": "Drizzle",
"p.wmo.55": "Dense drizzle",
"p.wmo.56": "Freezing drizzle",
"p.wmo.57": "Freezing drizzle",
"p.wmo.61": "Light rain",
"p.wmo.63": "Rain",
"p.wmo.65": "Heavy rain",
"p.wmo.66": "Freezing rain",
"p.wmo.67": "Freezing rain",
"p.wmo.71": "Light snow",
"p.wmo.73": "Snow",
"p.wmo.75": "Heavy snow",
"p.wmo.77": "Snow grains",
"p.wmo.80": "Rain showers",
"p.wmo.81": "Showers",
"p.wmo.82": "Violent showers",
"p.wmo.85": "Snow showers",
"p.wmo.86": "Heavy snow showers",
"p.wmo.95": "Thunderstorm",
"p.wmo.96": "Thunderstorm with hail",
"p.wmo.99": "Thunderstorm with hail",
"p.wmo.undefined": "–"
},
"uk": {
"p.act.wozek": "Візок",
"p.act.nosidlo": "Кенгуру",
"p.act.spacer": "Прогулянка",
"p.act.plac": "Майданчик",
"p.act.wozek.d": "лежить або сидить",
"p.act.nosidlo.d": "біля батьків",
"p.act.spacer.d": "іде сам",
"p.act.plac.d": "бігає",
"p.band.hot": "Спека",
"p.band.warm": "Тепло",
"p.band.mild": "Помірно",
"p.band.cool": "Прохолодно",
"p.band.cold": "Холодно",
"p.band.frost": "Дуже холодно",
"p.band.severe": "Екстремально холодно",
"p.why.newborn": "новонароджений −1°",
"p.why.long": "довга прогулянка −1°",
"p.o.hot.b1": "Лише боді з коротким рукавом або без рукавів (бавовна, льон)",
"p.o.hot.b2": "Вільна футболка з коротким рукавом (бавовна, льон)",
"p.o.hot.l1": "Лише підгузок або тонкі шорти",
"p.o.hot.l2": "Шорти або легка сукня",
"p.o.hot.f1": "Сандалі із закритими пальцями",
"p.o.hot.f2": "Босоніж",
"p.o.hot.h": "Світлий легкий капелюх із крисами",
"p.o.warm.b1": "Футболка або боді з коротким рукавом",
"p.o.warm.b2": "Тонка кофта на блискавці",
"p.o.warm.l": "Тонкі довгі штани або легінси",
"p.o.warm.f1": "Шкарпетки й легке взуття",
"p.o.warm.f2": "Тонкі шкарпетки",
"p.o.warm.h1": "Капелюх або кепка",
"p.o.warm.h2": "Тонка шапочка, лише при вітрі",
"p.o.warm.h3": "Без шапки",
"p.o.mild.b1": "Боді або футболка з довгим рукавом",
"p.o.mild.b2": "Тонка кофта або светрик",
"p.o.mild.b3": "Вітрівка або тонка куртка",
"p.o.mild.b4": "Тонка куртка",
"p.o.mild.l": "Довгі штани (спортивні, бавовняні)",
"p.o.mild.f1": "Шкарпетки й закрите взуття",
"p.o.mild.f2": "Шкарпетки",
"p.o.mild.h1": "Тонка бавовняна шапка",
"p.o.mild.h2": "Тонка шапка при вітрі",
"p.o.cool.b2": "Фліс або кофта",
"p.o.cool.b3": "Демісезонна куртка",
"p.o.cool.l1": "Колготки + довгі штани",
"p.o.cool.l2": "Довгі штани",
"p.o.cool.f1": "Товстіші шкарпетки й демісезонне взуття",
"p.o.cool.f2": "Товстіші шкарпетки",
"p.o.cool.h": "Тонка шапка, що закриває вуха",
"p.o.cool.n": "Снуд або хустинка",
"p.o.cool.hd": "Тонкі рукавички",
"p.o.cold.b2": "Фліс або светр",
"p.o.cold.b3a": "Утеплений комбінезон",
"p.o.cold.b3b": "Утеплена куртка",
"p.o.cold.l1": "Колготки + штани (під комбінезон)",
"p.o.cold.l2": "Колготки + штани або утеплені штани",
"p.o.cold.f1": "Теплі шкарпетки й утеплене взуття",
"p.o.cold.f2": "Теплі шкарпетки або пінетки для візка",
"p.o.cold.h": "Тепла шапка на вуха",
"p.o.cold.n": "Снуд",
"p.o.cold.hd1": "Рукавички",
"p.o.cold.hd2": "Рукавички-варіжки для немовлят",
"p.o.frost.b1": "Термобілизна або боді з вовни мериноса",
"p.o.frost.b2": "Фліс або вовняний светр",
"p.o.frost.b3": "Зимовий комбінезон",
"p.o.frost.l": "Вовняні колготки або термолегінси (під комбінезон)",
"p.o.frost.f1": "Вовняні шкарпетки й зимове взуття",
"p.o.frost.f2": "Вовняні шкарпетки, пінетки або конверт, що закриває ніжки",
"p.o.frost.h1": "Балаклава й зимова шапка",
"p.o.frost.h2": "Зимова шапка, за потреби балаклава",
"p.o.frost.n": "Флісовий снуд",
"p.o.frost.hd": "Непромокальні рукавиці",
"p.o.wet.b": "Дощовик як верхній шар",
"p.o.wet.l": "Непромокальні штани зверху",
"p.o.wet.f1": "Гумові чоботи з теплою вкладкою",
"p.o.wet.f2": "Гумові чоботи",
"p.o.snow.l": "Непромокальні штани (сніг)",
"p.o.snow.hd": "Запасна пара рукавичок",
"p.o.plac.1": "Запасні шкарпетки й штани",
"p.o.plac.2": "Зніміть кофту після 10 хв гри, якщо дитині жарко",
"p.o.st.1": "Без ковдри. Не накривайте капюшон пелюшкою: всередині стає жарко",
"p.o.st.2": "Тонкий мусліновий плед",
"p.o.st.3": "Плед або тонкий конверт",
"p.o.st.4": "Конверт для візка",
"p.o.st.5": "Зимовий конверт для візка й вітрозахист",
"p.o.st.rain": "Дощовик, трохи відкритий для вентиляції",
"p.o.st.wind": "Капюшон повернутий до вітру",
"p.o.car.1": "Одягніть дитину на один шар легше. Тепло батьків зігріває",
"p.o.car.2": "Слінгокуртка або чохол на кенгуру, теплі шкарпетки (ніжки стирчать)",
"p.a.severe.t": "Подумайте про коротшу прогулянку",
"p.a.severe.i": "За такої відчутної температури виходьте з немовлям щонайбільше на 15–20 хвилин або залишайтеся вдома.",
"p.a.severe.w": "Вийдіть на 20–30 хвилин і стежте за щоками й носом.",
"p.a.heat": "Уникайте виходу між 11 і 16 годиною. Частіше давайте груди, молоко або воду (воду з 6 місяців). Шукайте тінь.",
"p.a.uv.inf": "Немовлят до 6 місяців тримайте в тіні, захищайте одягом і капюшоном візка. Сонцезахисний крем у такому віці не використовують.",
"p.a.rain.t": "Можливий дощ",
"p.a.rain.car": "Візьміть парасольку або дощовик для кенгуру.",
"p.a.rain.st": "Дощовик для візка — у кошику.",
"p.a.rain.w": "Непромокальний одяг уже є в списку.",
"p.a.wind.t": "Сильний вітер",
"p.a.seat.t": "Автокрісло",
"p.a.seat": "Перед пристібанням в автокріслі зніміть куртку чи комбінезон. Товстий шар послаблює ремені. Накрийте дитину ковдрою поверх ременів.",
"p.a.neck.t": "Тест шиї",
"p.a.neck": "Торкніться шиї через 10 хвилин. Тепла й суха: добре. Спітніла: зніміть шар. Прохолодна: додайте. Холодні долоні — це нормально й нічого не означають.",
"p.r.snow": "сніг",
"p.r.now": "Зараз",
"p.r.sample": "Приклад прогнозу. Коли застосунок працює з власної адреси, він завантажує справжню погоду для вашого місця.",
"p.r.err": "У цьому попередньому перегляді немає зʼєднання з погодним сервісом. Показую приклад осіннього прогнозу. Після розгортання на власній адресі застосунок завантажує справжню погоду.",
"p.sl.head": "Голова",
"p.sl.neck": "Шия",
"p.sl.body": "Тулуб",
"p.sl.legs": "Ноги",
"p.sl.feet": "Стопи",
"p.sl.hands": "Руки",
"p.sl.bag": "У сумку",
"p.kid.default": "Малюк",
"p.loc.yours": "Ваше місце",
"p.s.feel.cold": "Мерзлячок",
"p.s.feel.typ": "Звичайно",
"p.s.feel.hot": "Швидко пітніє",
"p.s.findloc": "Шукаю місцезнаходження…",
"p.s.locfail": "Не вдалося визначити місцезнаходження. Дозвольте доступ у браузері або введіть населений пункт.",
"p.settings": "Налаштування",
"p.ex.b": "Приклад дитини.",
"p.ex.d": "Налаштуйте свою за 3 кроки, і поради підлаштуються під вік.",
"p.ex.go": "Почати",
"p.wx": "Погода",
"p.when": "Коли виходите?",
"p.what": "Що робите",
"p.dur": "Як довго",
"p.rec": "Рекомендація",
"p.outfit": "Що вдягнути",
"p.outfit.h": "Що вдягнути · від шкіри назовні",
"p.tips": "Поради",
"p.m.sum": "Змінити умови вручну",
"p.m.d": "Замінює прогноз. Корисно, щоб перевірити, як зміниться одяг.",
"p.m.t": "Відчувається °C",
"p.m.w": "Вітер км/год",
"p.m.p": "Імовірність опадів %",
"p.m.u": "УФ-індекс",
"p.m.k": "Опади",
"p.k.none": "немає",
"p.k.rain": "дощ",
"p.k.snow": "сніг",
"p.m.apply": "Перерахувати",
"p.m.reset": "Повернутися до прогнозу",
"p.f.back": "← Усі модулі",
"p.f.note": " · Погода: Open-Meteo. Поради загальні. Завжди перевіряйте шию дитини.",
"p.feels": "відчувається як {v}°",
"p.stat.wind": "Вітер",
"p.stat.max": "Макс. сьогодні",
"p.stat.min": "Мін.",
"p.kmh": "км/год",
"p.addkid": "+ дитина",
"p.why.cold": "мерзлячок {v}°",
"p.why.warm": "швидко зігрівається +{v}°",
"p.a.frost": "Скоротіть прогулянку до 30–40 хвилин. Нанесіть на щоки жирний захисний крем від холоду (без води) за 20 хвилин до виходу.",
"p.a.uv": "Мінеральний сонцезахисний крем SPF 50 на відкриту шкіру{x}.",
"p.a.uv.glasses": ", окуляри UV400",
"p.a.rain": "Імовірність опадів до {p}%. {x}",
"p.a.wind": "Пориви до {v} км/год. Снуд, захист обличчя, уникайте відкритих просторів.",
"p.v.label": "{name} · {age} · вихід о {time}",
"p.v.manual": "(вручну)",
"p.v.title": "{band}: {n} {w} на тулуб",
"p.v.why": "Температура для дитини {T}°. Розрахована з найнижчої відчутної температури під час прогулянки ({f}°) і поправок: {why}.",
"p.s.step": "Крок {n} з 3",
"p.s.who": "Кого вдягаємо?",
"p.s.name": "Імʼя або прізвисько",
"p.s.name.ph": "напр. Тарасик",
"p.s.birth": "Місяць народження",
"p.s.feel": "Як переносить холод?",
"p.s.cancel": "Скасувати",
"p.s.next": "Далі",
"p.s.back": "Назад",
"p.s.where": "Де гуляєте?",
"p.s.gps": "Використати моє місцезнаходження",
"p.s.cur": "Зараз: {v}",
"p.s.city": "або введіть населений пункт",
"p.s.city.ph": "напр. Вроцлав",
"p.s.nores": "Нічого не знайдено.",
"p.s.geofail": "Пошук населених пунктів не відповідає. Спробуйте пізніше.",
"p.s.how": "Як зазвичай виходите?",
"p.s.later": "Це можна змінити перед кожним виходом.",
"p.s.done": "Готово",
"p.title": "Погода · Wyprawka",
"p.wmo.0": "Ясно",
"p.wmo.1": "Переважно сонячно",
"p.wmo.2": "Мінлива хмарність",
"p.wmo.3": "Хмарно",
"p.wmo.45": "Туман",
"p.wmo.48": "Паморозь",
"p.wmo.51": "Легка мряка",
"p.wmo.53": "Мряка",
"p.wmo.55": "Густа мряка",
"p.wmo.56": "Крижана мряка",
"p.wmo.57": "Крижана мряка",
"p.wmo.61": "Невеликий дощ",
"p.wmo.63": "Дощ",
"p.wmo.65": "Злива",
"p.wmo.66": "Крижаний дощ",
"p.wmo.67": "Крижаний дощ",
"p.wmo.71": "Невеликий сніг",
"p.wmo.73": "Сніг",
"p.wmo.75": "Сильний сніг",
"p.wmo.77": "Снігова крупа",
"p.wmo.80": "Короткочасний дощ",
"p.wmo.81": "Короткочасні опади",
"p.wmo.82": "Сильні зливи",
"p.wmo.85": "Короткочасний сніг",
"p.wmo.86": "Хуртовина",
"p.wmo.95": "Гроза",
"p.wmo.96": "Гроза з градом",
"p.wmo.99": "Гроза з градом",
"p.wmo.undefined": "–"
}
});
